#!/usr/bin/perl  -w

use lib '/usr/share/postgresql-common';
use PgCommon;
use Getopt::Long;
use POSIX qw/setlocale LC_ALL/;

if ($#ARGV != 4) {
	print "Usage: $0 [version] [clustername] [configfile] [parameter] [value]\n";
	exit 1;
}

($version) = $ARGV[0];
($clustername) = $ARGV[1];# =~ /^([-.\w]+)^$/;
($configfile) = $ARGV[2];# =~ /^([-.\w\.]+)^$/;
($parameter) = $ARGV[3];# =~ /^([-_.\w\.]+)^$/;
($value) = $ARGV[4];

error "invalid cluster name" unless defined $clustername;
error "invalid configfile" unless defined $configfile;
error "invalid parameter" unless defined $parameter;

print "$version, $clustername, $configfile: $parameter => $value\n";

PgCommon::set_conf_value $version, $clustername, $configfile, $parameter, $value;
